In [50]:
import os
import glob
import numpy as np

In [ ]:
#9/27/23 Recompute drift and decoding on D9
#scope1Ana1: P34 all old drift and decoded move to old_decoded folder, finished
#scope1Ana1: E1 all old drift and decoded move to old_decoded folder, OVERwrite fov10...
#scope1Ana2: P12 OVERwrite old D9 decoded_new diftNew...some computing failed
#Scope2Ana2: P56 overwrite, fail some of compute
#Scope2Ana2: E2 old files copied
#Scope1: P711, old files copied

In [108]:
save_folders = [r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP12',
                r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP34',
                r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisE1',
                r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisP56',
                r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisP711',
                r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisE2']

In [110]:
for fld in save_folders:
    old_fls = glob.glob(fld+r'\d*')
    len(old_fls)
    old_fls = [fl for fl in old_fls if 'drift' in os.path.basename(fl) or 'decoded' in os.path.basename(fl)]
    print(len(old_fls))

44
120
120
120
120
120


In [ ]:
### 35 in P711 is bad
### 1,7,28 in E2 is bad

In [107]:
np.setdiff1d(np.arange(60),np.sort([e.split('__')[-1].split('--')[0] for e in old_fls if 'decoded' in e]).astype(int))

array([ 1,  7, 28])

In [88]:
import shutil
from tqdm import tqdm

In [89]:
master_folder=  os.path.dirname(old_fls[0])
new_folder = master_folder+r'\old_decoding'
if not os.path.exists(new_folder): os.makedirs(new_folder)
for fl in tqdm(old_fls):
    if os.path.exists(fl):
        flT = fl.replace(master_folder,new_folder)
        shutil.move(fl,flT)
        #print(fl,flT)

100%|█████████████████████████████████████████████████████████████████████████████| 3187/3187 [00:22<00:00, 144.04it/s]


In [75]:
driftfl = r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisP56\driftNew_Conv_zscan__15--_D9.pkl'
drifts,flds_,fov_,fl_ref = np.load(driftfl,allow_pickle=True)
drift_dicN = {os.path.basename(fld):drft[0] for drft,fld in zip(drifts,flds_)}

In [73]:
driftfl = '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP34\\\old_decoding\\driftNew_Conv_zscan__15--_D9.pkl'
drifts,flds_,fov_,fl_ref = np.load(driftfl,allow_pickle=True)
drift_dicO = {os.path.basename(fld):drft[0] for drft,fld in zip(drifts,flds_)}

In [74]:
[drift_dicN[key]-drift_dicO[key]for key in drift_dicN]

[array([ -0.20891249,  20.96462488, -13.54954369]),
 array([ -0.90874073,  18.03211305, -12.01506605]),
 array([  0.55557065,  17.84967058, -11.32642786]),
 array([-0.32870588, 17.17762108, -8.88966219]),
 array([ -0.85301457,  16.61037676, -10.91316795]),
 array([ 0.12925022, 16.62693734, -7.69775288]),
 array([-0.16099065, 16.53435599, -8.33902261]),
 array([-0.29438385, 14.71306687, -8.99632948]),
 array([0., 0., 0.]),
 array([ 0.09050335,  0.21319285, -0.2081747 ]),
 array([-0.07195553,  0.31716886, -0.49991976]),
 array([ 0.09576395,  2.46046114, -2.38209172]),
 array([ 1.43919772,  6.17643203, -5.48476558]),
 array([ 0.18234837,  5.68304358, -0.57466509]),
 array([ 0.09493687, -1.52645896,  1.38426236]),
 array([-0.13010142,  0.15688101,  0.22324241])]

In [71]:
[drift_dicN[key]-drift_dicO[key]for key in drift_dicN]

[array([ -0.20891249,  20.96462488, -13.54954369]),
 array([ -0.90874073,  18.03211305, -12.01506605]),
 array([  0.55557065,  17.84967058, -11.32642786]),
 array([-0.32870588, 17.17762108, -8.88966219]),
 array([ -0.85301457,  16.61037676, -10.91316795]),
 array([ 0.12925022, 16.62693734, -7.69775288]),
 array([-0.16099065, 16.53435599, -8.33902261]),
 array([-0.29438385, 14.71306687, -8.99632948]),
 array([0., 0., 0.]),
 array([ 0.09050335,  0.21319285, -0.2081747 ]),
 array([-0.07195553,  0.31716886, -0.49991976]),
 array([ 0.09576395,  2.46046114, -2.38209172]),
 array([ 1.43919772,  6.17643203, -5.48476558]),
 array([ 0.18234837,  5.68304358, -0.57466509]),
 array([ 0.09493687, -1.52645896,  1.38426236]),
 array([-0.13010142,  0.15688101,  0.22324241])]

In [13]:
save_folder_FinalDecodedSpots = r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\FinalDecodedSpots'
fls_FDS = glob(save_folder_FinalDecodedSpots+os.sep+'*Analysis*.npz')
len(fls_FDS)

1390

In [26]:
E1=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisE1*.npz')
E2=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisE2*.npz')
P12=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisP12*.npz')
P34=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisP34*.npz')
P56=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisP56*.npz')
P12=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisP12*.npz')
P711=glob(save_folder_FinalDecodedSpots+os.sep+'*AnalysisP711*.npz')
print(len(E1),len(E2), len(P12),len(P34),len(P56),len(P711))

130 258 241 258 257 259


In [29]:
save_folder_drifta = r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\DriftAcrossDatasets'
fls_drifta = glob(save_folder_drifta+os.sep+'*dapiFeatures.npz')
len(fls_drifta)
#628

5581

In [45]:
D7=glob(save_folder_drifta+os.sep+'*D7*.npz')
D9=glob(save_folder_drifta+os.sep+'*D9*.npz')
D13=glob(save_folder_drifta+os.sep+'*D13*.npz')
D14=glob(save_folder_drifta+os.sep+'*D14*.npz')
D16=glob(save_folder_drifta+os.sep+'*D16*.npz')
allf=[len(D7),len(D9),len(D13),len(D14),len(D16)]
print(len(D7),len(D9),len(D13),len(D14),len(D16),sum(allf))


217 420 1337 1792 1815 5581


In [47]:
A1=glob(save_folder_drifta+os.sep+'*A1*.npz')
len(A1)

797

In [70]:
H1=glob(save_folder_drifta+os.sep+'*H1_*.npz')
H17=glob(save_folder_drifta+os.sep+'*H17*.npz')
H33=glob(save_folder_drifta+os.sep+'*H33*.npz')
H49=glob(save_folder_drifta+os.sep+'*H49*.npz')
H65=glob(save_folder_drifta+os.sep+'*H65*.npz')
H81=glob(save_folder_drifta+os.sep+'*H81*.npz')
print(len(H1),len(H17),len(H33),len(H49),len(H65),len(H81))

798 797 797 798 797 797


In [59]:
D7_H49=glob(save_folder_drifta+os.sep+'*H49_MER_D7*.npz')
D9_H49=glob(save_folder_drifta+os.sep+'*H49_MER_D9*.npz')
D13_H49=glob(save_folder_drifta+os.sep+'*H49_MER_D13*.npz')
D14_H49=glob(save_folder_drifta+os.sep+'*H49_MER_D14*.npz')
D16_H49=glob(save_folder_drifta+os.sep+'*H49_MER_D16*.npz')
print(len(D7_H49),len(D9_H49),len(D13_H49),len(D14_H49),len(D16_H49))

31 60 191 256 260


In [65]:
#print(len(D7),len(D9),len(D13),len(D14),len(D16),sum(allf))
#7H=H1+H17+H33+H49+H65+H81+A
H49_D=[31, 60, 191, 256, 260]
b=[x*7 for x in H49_D]
b

[217, 420, 1337, 1792, 1820]

In [63]:
print(sum(b))

5586


In [68]:
D7_H1=glob(save_folder_drifta+os.sep+'*H1_MER_D7*.npz')
D9_H1=glob(save_folder_drifta+os.sep+'*H1_MER_D9*.npz')
D13_H1=glob(save_folder_drifta+os.sep+'*H1_MER_D13*.npz')
D14_H1=glob(save_folder_drifta+os.sep+'*H1_MER_D14*.npz')
D16_H1=glob(save_folder_drifta+os.sep+'*H1_MER_D16*.npz')
print(len(D7_H1),len(D9_H1),len(D13_H1),len(D14_H1),len(D16_H1))

31 60 191 256 260


# ScopeAnalysis1

# Scope1Ana1
#P34 driftNew: 797
#P34 decodedNew: 794
#E1 driftNew: 797
#E1 decodedNew: 793

# Scope2Ana2
#p56 driftNew: 797
#p56 decodedNew: 797
#E2 driftNew: 797
#E2 decodedNew: 786

# Scope1Ana2:
#P12 driftNew: 797
#P12 decodedNew:782

# Scope1
#P711 driftNew: 797
#P711 decodedNew: 797

In [ ]:
Delete res....npz



### from ioMicro.py 
serach for: np.savez(self.res_fl,res_unfolder=res_unfolder,lens=lens)

comment out: #np.savez(self.res_fl,res_unfolder=res_unfolder,lens=lens)



In [1]:
#C:\Scripts\NMERFISH\
set_ifov = '_D16',59
import worker_Scope1__EmbryoPlateE1V2 as wkr
wkr.get_files(set_ifov,iHm=wkr.iHm,iHM=wkr.iHM)

('\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisE1',
 ['\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H65_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H66_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H67_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H68_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H69_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H70_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H71_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H72_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H73_MER_D16',
  '\\\\192.168.0.6\\bbfishjoy4\\CGBB_embryo_4_28_2023\\H74_MER_D16',
  '\\\\192.168.0.7\\bbfishmahsa\\CGBB_embryo_4_28_2023\\H74_lowMER_D16',
  '\\\\192.168.0.7\\bbfishmahsa\\CGBB_embryo_4_28_2023\\H75_lowMER_D16',
  '\\\\192.168.0.7\\bbfishmahsa\\CGBB_embryo_4_28_2023\\H75_MER_D16',
  '\\\\192.168.0.7\\bbfishmahsa\\CGBB

In [ ]:
all_flds
for master_folder in master_data_folders:
    #all_flds = glob.glob(r'\\192.168.0.6\bbfishjoy4\CGBB_embryo_4_28_2023\H*MER_*')
    all_flds = glob.glob(master_folder+r'\H*MER*')

In [9]:
wkr.iHM,wkr.iHm

(80, 65)

In [38]:
save_folder_P34= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP34'
fls_P34_decodedNew = glob(save_folder_P34+os.sep+'decodedNew*.npz')
len(fls_P34_decodedNew)

60

In [41]:

save_folder_E1= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisE1'
fls_E1_decodedNew = glob(save_folder_E1+os.sep+'decodedNew*.npz')
len(fls_E1_decodedNew)
#690

60

In [2]:
#ScopeAnalysis1
#save_folder_P34= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP34'

In [50]:
# save_folder_P34= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP34'
# fls_P34_decodedNew = glob(save_folder_P34+os.sep+'decodedNew*.npz')
# len(fls_P34_decodedNew)
# #794

794

In [222]:
times = [os.path.getctime(fl) for fl in fls_P34_decodedNew]
seconds_per_file = np.mean(np.diff(np.sort(times))[-50:]) #seconds per file

In [225]:
800*seconds_per_file/3600/24

3.9046009776327346

In [31]:
fls_E1_driftNew=glob(save_folder_E1+os.sep+'driftNew*.pkl')
len(fls_E1_driftNew)
#320

370

In [9]:
save_folder_drifta = r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\DriftAcrossDatasets'

# Scope1Analysis2

In [5]:
#Scope1Analysis2


In [42]:
save_folder_P12= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP12'
fls_P12_decoded = glob(save_folder_P12+os.sep+'decodedNew*.npz')
len(fls_P12_decoded)
#782


797

In [54]:
np.unique([fl.split('_')[-1]for fl in fls_P12_decoded],return_counts=True)

(array(['D13.npz', 'D14.npz', 'D16.npz', 'D7.npz', 'D9.npz'], dtype='<U7'),
 array([165, 237, 206,  31,  42], dtype=int64))

In [55]:
np.unique([fl.split('_')[-1]for fl in fls_P34_decodedNew],return_counts=True)


(array(['D13.npz', 'D14.npz', 'D16.npz', 'D7.npz', 'D9.npz'], dtype='<U7'),
 array([188, 256, 259,  31,  60], dtype=int64))

In [56]:
#np.sort(fls_P12_decoded)

In [84]:
fls_P12_driftNew=glob(save_folder_P12+os.sep+'driftNew_*.pkl')
len(fls_P12_driftNew)
#789

797

In [180]:
fls_P12_decoded = glob(save_folder_P12+os.sep+'decoded*.npz')

# Scope2Analysis2

In [9]:
#Scope2Analysis2
#save_folder_P56 =r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP56'
#save_folder_PE2 =r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisPE2'

In [81]:
save_folder_P56 =r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisP56'
fls_P56_decoded = glob(save_folder_P56+os.sep+'decodedNew*.npz')
fls_P56_driftNew=glob(save_folder_P56+os.sep+'driftNew*.pkl')
print(len(fls_P56_decoded),len(fls_P56_driftNew))

793 797


In [87]:
save_folder_E2 =r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisE2'
fls_E2_decoded = glob(save_folder_E2+os.sep+'decodedNew*.npz')
len(fls_E2_decoded)
#786

786

In [73]:
fls_E2_driftNew=glob(save_folder_E2+os.sep+'driftNew*.pkl')
len(fls_E2_driftNew)
#797

797

# Scope1Microscope

In [12]:
#Scope1Microscope
save_folder_P711 =r'\\192.168.0.7\bbfishmahsa3\CGBB_embryo_4_28_2023\MERFISH_AnalysisP711'

In [48]:
fls_P711_decoded = glob(save_folder_P711+os.sep+'decodedNew*.npz')
len(fls_P711_decoded)
#747/  7/28/23 copy new ioMicro with decodedNew

797

In [14]:
import numpy as np
np.sort(fls_P711_decoded)

array(['\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__00--_D7.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__00--_D9.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__000--_D13.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__000--_D14.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__000--_D16.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__001--_D13.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__001--_D14.npz',
       '\\\\192.168.0.7\\bbfishmahsa3\\CGBB_embryo_4_28_2023\\MERFISH_AnalysisP711\\decodedNew_Conv_zscan__001--_D16.npz',
       '\\\\192.168.

In [49]:
fls_P711_driftNew=glob(save_folder_P711+os.sep+'driftNew*.pkl')
len(fls_P711_driftNew)
#747



797

In [ ]:
import sys
master_analysis_folder = r'C:\Users\BintuLabUser\BintuLabScripts1\MERFISH_DC_SCOPE2\smFISHAnalysisHuman'
sys.path.append(master_analysis_folder)
from ioMicro import *

In [121]:
#save_folder =r'X:\Glass_MERFISH\CGBB_ChrX_04_16_2023_Analysis'
save_folder= r'\\192.168.0.6\bbfishjoy4extra\MERFISH_AnalysisP12'


In [122]:
save_folder

'\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12'

In [42]:
import os
for file in os.listdir(save_folder):
    print(file)

fovs___D16.npy
Conv_zscan__059--H17_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H17_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H17_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H18_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H18_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H18_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H19_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H19_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H19_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H20_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H20_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H20_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H21_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H21_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H21_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H22_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H22_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H22_MER_D16--col2__Xhfits.npz
Conv_zscan__059--H23_MER_D16--col0__Xhfits.npz
Conv_zscan__059--H23_MER_D16--col1__Xhfits.npz
Conv_zscan__059--H23_MER_D16--col2__Xhfits.np

In [123]:
fls_ = glob(save_folder+os.sep+'*.npz')
#fls_ = glob.glob(save_folder+os.sep+'*_Xh_RNAs.pkl')

In [130]:
fls_1 = glob(save_folder+os.sep+'decoded*.npz')

In [124]:
fls_2 = glob(save_folder+os.sep+ 'Conv_zscan__*.npz')

In [132]:
len(fls_1)

941

In [133]:
fls_1

['\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__059--_D16.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__000--_D14.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__000--_D13.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__250--_D16.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__250--_D14.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__000--_D16.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__251--_D16.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__001--_D14.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__001--_D13.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_zscan__251--_D14.npz',
 '\\\\192.168.0.6\\bbfishjoy4extra\\MERFISH_AnalysisP12\\decoded_Conv_

In [129]:
len(np.unique(fls_2))

48561

In [126]:
len(fls_2)

48561

In [53]:
fls_1=fls_[:3]

In [ ]:
fls_1

In [52]:
np.unique([fl.split('--')[1]for fl in fls_1 if '_C' in fl.split('--')[1]],return_counts=True)

(array([], dtype=float64), array([], dtype=int64))

In [62]:
np.unique([os.path.basename(fl).split('--')[0] for fl in fls_2])

array(['decoded_Conv_zscan__00', 'decoded_Conv_zscan__000',
       'decoded_Conv_zscan__001', 'decoded_Conv_zscan__002',
       'decoded_Conv_zscan__003', 'decoded_Conv_zscan__004',
       'decoded_Conv_zscan__005', 'decoded_Conv_zscan__006',
       'decoded_Conv_zscan__007', 'decoded_Conv_zscan__008',
       'decoded_Conv_zscan__009', 'decoded_Conv_zscan__01',
       'decoded_Conv_zscan__010', 'decoded_Conv_zscan__011',
       'decoded_Conv_zscan__012', 'decoded_Conv_zscan__013',
       'decoded_Conv_zscan__014', 'decoded_Conv_zscan__015',
       'decoded_Conv_zscan__016', 'decoded_Conv_zscan__017',
       'decoded_Conv_zscan__018', 'decoded_Conv_zscan__019',
       'decoded_Conv_zscan__02', 'decoded_Conv_zscan__020',
       'decoded_Conv_zscan__021', 'decoded_Conv_zscan__022',
       'decoded_Conv_zscan__023', 'decoded_Conv_zscan__024',
       'decoded_Conv_zscan__025', 'decoded_Conv_zscan__026',
       'decoded_Conv_zscan__027', 'decoded_Conv_zscan__028',
       'decoded_Conv_zscan_

In [56]:
np.unique([os.path.basename(fl).split('--')[0] for fl in fls_1])

array(['Conv_zscan__059'], dtype='<U15')

In [59]:
np.unique([os.path.basename(fl).split('--')[2] for fl in fls_1])

array(['col0__Xhfits.npz', 'col1__Xhfits.npz', 'col2__Xhfits.npz'],
      dtype='<U16')

In [58]:
np.unique([os.path.basename(fl).split('--')[-1] for fl in fls_1])

array(['col0__Xhfits.npz', 'col1__Xhfits.npz', 'col2__Xhfits.npz'],
      dtype='<U16')

In [29]:
np.unique([fl.split('--')[1]for fl in fls_ if '_C' in fl.split('--')[1]],return_counts=True)

(array(['H10_R28,R29,R30_C', 'H11_R31,R32,R33_C', 'H12_R34,R35,R36_C',
        'H13_R37,R38,R39_C', 'H14_R40,R41,R42_C', 'H15_R43,R44,R45_C',
        'H16_R46,R47,R48_C', 'H17_R49,R50,R51_C', 'H18_R52,R53,R54_C',
        'H19_R55,R56,R57_C', 'H1_R1,R2,R3_C', 'H20_R58,R59,R60_C',
        'H21_R61,R62,R63_C', 'H22_R64,R65,R66_C', 'H23_R67,R68,R69_C',
        'H24_R70,R71,R72_C', 'H25_R73,R74,R75_C', 'H26_R76,R77,R78_C',
        'H27_R79,R80,R81_C', 'H28_R82,R83,R84_C', 'H29_R85,R86,R87_C',
        'H2_R4,R5,R6_C', 'H30_R88,R89,R90_C', 'H31_R91,R92,R93_C',
        'H32_R94,R95,R96_C', 'H33_R97,R98,R99_C', 'H34_Q200,201,202_C',
        'H35_Q1,2,3_C', 'H36_Q4,5,6_C', 'H37_Q16,17,18_C',
        'H38_Q28,29,30_C', 'H39_Q58,59,60_C', 'H3_R7,R8,R9_C',
        'H40_Q61,62,63_C', 'H41_Q10,11,12_C', 'H42_Q13,14,15_C',
        'H43_Q40,41,42_C', 'H44_Q52,53,54_C', 'H45_Q73,74,75_C',
        'H4_R10,R11,R12_C', 'H5_R13,R14,R15_C', 'H6_R16,R17,R18_C',
        'H7_R19,R20,R21_C', 'H8_R22,R23,R24_C', 

In [25]:
np.unique([fl.split('--')[1]for fl in fls_ if '_C' in fl.split('--')[1]],return_counts=True)

(array(['H10_R28,R29,R30_C', 'H11_R31,R32,R33_C', 'H12_R34,R35,R36_C',
        'H13_R37,R38,R39_C', 'H14_R40,R41,R42_C', 'H15_R43,R44,R45_C',
        'H16_R46,R47,R48_C', 'H17_R49,R50,R51_C', 'H18_R52,R53,R54_C',
        'H19_R55,R56,R57_C', 'H1_R1,R2,R3_C', 'H20_R58,R59,R60_C',
        'H21_R61,R62,R63_C', 'H22_R64,R65,R66_C', 'H23_R67,R68,R69_C',
        'H24_R70,R71,R72_C', 'H25_R73,R74,R75_C', 'H26_R76,R77,R78_C',
        'H27_R79,R80,R81_C', 'H28_R82,R83,R84_C', 'H29_R85,R86,R87_C',
        'H2_R4,R5,R6_C', 'H30_R88,R89,R90_C', 'H31_R91,R92,R93_C',
        'H32_R94,R95,R96_C', 'H33_R97,R98,R99_C', 'H34_Q200,201,202_C',
        'H35_Q1,2,3_C', 'H36_Q4,5,6_C', 'H37_Q16,17,18_C',
        'H38_Q28,29,30_C', 'H39_Q58,59,60_C', 'H3_R7,R8,R9_C',
        'H40_Q61,62,63_C', 'H41_Q10,11,12_C', 'H42_Q13,14,15_C',
        'H43_Q40,41,42_C', 'H44_Q52,53,54_C', 'H45_Q73,74,75_C',
        'H4_R10,R11,R12_C', 'H5_R13,R14,R15_C', 'H6_R16,R17,R18_C',
        'H7_R19,R20,R21_C', 'H8_R22,R23,R24_C', 

In [15]:
asm = analysis_smFISH(data_folders = [r'X:\Glass_MERFISH\CGBB_ChrX_04_16_2023\H*R*','Y:\Glass_MERFISH\CGBB_ChrX_04_16_2023\H*Q*'],
                     save_folder =r'X:\Glass_MERFISH\CGBB_ChrX_04_16_2023_Analysis',
                     H0folder=  r'X:\Glass_MERFISH\CGBB_ChrX_04_16_2023\H0_*',exclude_H0=True)
set_ = '_C'
asm.set_set(set_)

Found files:240
Found hybe folders:90


In [19]:
#asm.Qfolders

In [1]:
from worker_smFISHDNA import *

In [3]:
f(['_C',50,'Q200'])#set_ifov_iQs

Found files:240
Found hybe folders:90
### define H0 and load background
Background file: X:\Glass_MERFISH\CGBB_ChrX_04_16_2023\H0_C\Conv_zscan__050.zarr
### load signal
Signal file: Y:\Glass_MERFISH\CGBB_ChrX_04_16_2023\H34_Q200,201,202_C\Conv_zscan__050.zarr
Found drift:[ 0 36 48]
Fitting color 0
Fraction of bk: 0.8823318034410477
Fitting color 1
Fraction of bk: 1.0837628841400146
Fitting color 2
Fraction of bk: 0.9619176983833313


In [ ]:
#Run in a new terminal (Anaconda terminal)
cd C:\Users\BintuLabUser\BintuLabScripts1\MERFISH_DC_SCOPE2\smFISHAnalysisHuman&&activate cellpose&&python worker_smFISHDNA.py